OFFICIAL_TEAM_NAMES = {
    "Alaves": "Deportivo Alavés",
    "Almeria": "UD Almería",
    "Ath Bilbao": "Athletic Bilbao",
    "Ath Madrid": "Club Atlético de Madrid",
    "Barcelona": "FC Barcelona",
    "Betis": "Real Betis Balompié",
    "Celta": "RC Celta de Vigo",
    "Cordoba": "Córdoba CF",
    "Eibar": "SD Eibar",
    "Elche": "Elche CF",
    "Espanol": "RCD Espanyol",
    "Getafe": "Getafe CF",
    "Girona": "Girona FC",
    "Granada": "Granada CF",
    "Hercules": "Hércules CF",
    "Huesca": "SD Huesca",
    "La Coruna": "Deportivo La Coruña",
    "Las Palmas": "UD Las Palmas",
    "Leganes": "CD Leganés",
    "Levante": "Levante UD",
    "Malaga": "Málaga CF",
    "Mallorca": "RCD Mallorca",
    "Osasuna": "CA Osasuna",
    "Real Madrid": "Real Madrid CF",
    "Santander": "Racing Santander",
    "Sevilla": "Sevilla FC",
    "Sociedad": "Real Sociedad",
    "Sp Gijon": "Sporting Gijón",
    "Valencia": "Valencia CF",
    "Valladolid": "Real Valladolid CF",
    "Vallecano": "Rayo Vallecano",
    "Villarreal": "Villarreal CF",
    "Zaragoza": "Real Zaragoza",
}
